apiVersion: v1
kind: ServiceAccount
metadata:
  name: nitro-kyc-sa
  namespace: default
  annotations:
    # IRSA: links this service account to the IAM role created by setup.sh
    # Replace <ACCOUNT_ID> with your AWS account ID
    eks.amazonaws.com/role-arn: arn:aws:iam::<ACCOUNT_ID>:role/nitro-kyc-pod-role
